name: waterbridge_mm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - statsmodels=0.13.5
  - scikit-learn=1.1.3
  - numpy=1.21.2
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scipy=1.7.1
  - jupyter=1.0.0
  - networkx
  - pip
  - pip:
    - pgmpy
    - arch
    - linearmodels
    - seaborn
